npm install -g clean-css-cli uglifycss js-beautify html-minifier uglify-js minjson svgo
npm install -g @11ty/eleventy
npm install -g css-purge
npm install -g @sanity/cli
npm install -g bundle-js
npm install -g imagemin
npm install -g uglifyjs
npm install -g degit
npm i -g purgecss
npm install -g prettier
npm install -g gatsby-cli
npm install -g gulp
npm i -g postcss-cli
npm install -g autoprefixer
npm install -g npm-check-updates
npm install -g eslint
npm i -g @squoosh/cli
npm i -g vercel
npm install -g replace-jquery